### ISSUE TITLE
Type filter buttons need to be clicked twice

### ISSUE THREAD

**Issue by lupomontero** [bouli/laboratoria-cesar#3]
Hi again @bouli,

Many thanks for addressing the issues I opened.

One last thing... 😰... I was reviewing this again and I spotted an issue when using the "Público/Amigos" buttons. The way state is managed at the moment results in the user having to click twice on the buttons in order for the view to change. See example:

![cesar-feed](https://user-images.githubusercontent.com/110297/42288443-51fd819a-7f80-11e8-92e1-c6cb69192f68.gif)

Could you track down this _bug_ and propose a fix.

Cheers,

Lupo

**Comment by bouli** [comment]
Hi @lupomontero !
It's fixed! =)

Regards,
Cesar.
//I forgot to close the issue with the comment ¬¬ (https://github.com/bouli/laboratoria-cesar/commit/0d0437dce029184e1c4389cacbe6ff4588946687)
